// Standard scaffold for a new ask-app. The shell HTML, base CSS and base JS helpers are written once at
// create time and are NEVER regenerated by the LLM (base.css / base.js are protected; index.html may be
// overridden only if the model insists). The model writes app-specific logic into index.js (+ small
// modules) and styling into app.css, reusing the base classes/helpers. See freezr_askapps_plan_v1.md.

// index.html — a body-only fragment (freezr wraps it). Everything renders into #ask-app via JS.
export const SHELL_HTML = `<div id="ask-app" class="aa-app"></div>
`

// askapp-base.css — shared, do-not-edit component/utility styles the model reuses.
export const BASE_CSS = `/* freezr ask-app base styles — do NOT edit. Add app styles in app.css. */
:root {
  --aa-fg: #1c2330; --aa-muted: #6b7686; --aa-line: #e5e9f0;
  --aa-accent: #2f6fed; --aa-card: #f7f9fc; --aa-bg: #fff;
}
.aa-app { font-family: system-ui, -apple-system, sans-serif; color: var(--aa-fg); line-height: 1.5; padding: 20px; max-width: 940px; margin: 0 auto; }
.aa-app h1 { font-size: 22px; margin: 0 0 4px; }
.aa-app h2 { font-size: 17px; margin: 20px 0 8px; }
.aa-muted { color: var(--aa-muted); font-size: 13px; }
.aa-card { background: var(--aa-card); border: 1px solid var(--aa-line); border-radius: 12px; padding: 16px; margin: 12px 0; }
.aa-row { display: flex; gap: 12px; flex-wrap: wrap; }
.aa-grid { display: grid; gap: 12px; }
/* tables */
.aa-table { width: 100%; border-collapse: collapse; font-size: 14px; }
.aa-table th, .aa-table td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--aa-line); }
.aa-table th { color: var(--aa-muted); font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: .03em; cursor: pointer; white-space: nowrap; }
.aa-table td.aa-num, .aa-table th.aa-num { text-align: right; font-variant-numeric: tabular-nums; }
.aa-table tbody tr:hover td { background: rgba(47, 111, 237, 0.05); }
/* stat tiles */
.aa-stat { background: var(--aa-card); border: 1px solid var(--aa-line); border-radius: 12px; padding: 14px 16px; min-width: 140px; }
.aa-stat-label { color: var(--aa-muted); font-size: 12px; text-transform: uppercase; letter-spacing: .03em; }
.aa-stat-value { font-size: 24px; font-weight: 700; margin-top: 4px; font-variant-numeric: tabular-nums; }
/* horizontal bars (div-based charts) */
.aa-bars { display: flex; flex-direction: column; gap: 6px; }
.aa-bar-row { display: grid; grid-template-columns: minmax(90px, 160px) 1fr auto; gap: 10px; align-items: center; font-size: 13px; }
.aa-bar-track { background: #eef2f8; border-radius: 6px; height: 18px; overflow: hidden; }
.aa-bar-fill { background: var(--aa-accent); height: 100%; }
.aa-badge { display: inline-block; background: #eef2f8; color: #2f4066; border-radius: 12px; padding: 2px 10px; font-size: 12px; }
.aa-empty, .aa-loading { color: var(--aa-muted); padding: 28px; text-align: center; }
/* "ask" button (top-left) — jumps back to editing this app in /creator/ask. Injected by askapp-boot.js. */
.aa-ask-btn { position: fixed; top: 10px; left: 12px; z-index: 1000; background: #fff; border: 1px solid #cdd6e6; border-radius: 8px; padding: 3px 12px; font-size: 13px; font-weight: 600; color: #2f4066; text-decoration: none; box-shadow: 0 1px 3px rgba(20, 28, 45, 0.12); }
.aa-ask-btn:hover { border-color: var(--aa-accent); color: var(--aa-accent); }
`

// askapp-base.js — shared, do-not-edit UI helpers. The model imports what it needs from './askapp-base.js'.
export const BASE_JS = `/* freezr ask-app base helpers — do NOT edit. import { table, barChart, statRow, ... } from './askapp-base.js' */
export const el = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n }
export const clear = (node) => { while (node && node.firstChild) node.removeChild(node.firstChild); return node }
export const fmtNum = (n, opts) => (typeof n === 'number' && isFinite(n)) ? n.toLocaleString(undefined, opts) : (n == null ? '' : String(n))
export const fmtMoney = (n, ccy) => (typeof n === 'number' && isFinite(n)) ? n.toLocaleString(undefined, { style: 'currency', currency: ccy || 'USD', maximumFractionDigits: 0 }) : ''
export const fmtDate = (ts) => { const d = new Date(ts); return isNaN(d.getTime()) ? '' : d.toLocaleDateString() }

// Page heading with optional subtitle.
export const heading = (parent, title, subtitle) => { const h = el('div'); h.appendChild(el('h1', null, title)); if (subtitle) h.appendChild(el('div', 'aa-muted', subtitle)); parent.appendChild(h); return h }

// Row of stat tiles. items: [{ label, value }]
export const statRow = (parent, items) => {
  const row = el('div', 'aa-row')
  for (const it of (items || [])) { const s = el('div', 'aa-stat'); s.appendChild(el('div', 'aa-stat-label', it.label)); s.appendChild(el('div', 'aa-stat-value', it.value)); row.appendChild(s) }
  parent.appendChild(row); return row
}

// Sortable table. columns: [{ key, label, num?, format?(value,row) }]; rows: array of objects.
export const table = (parent, columns, rows) => {
  const t = el('table', 'aa-table'); const thead = el('thead'); const htr = el('tr')
  let sortKey = null; let sortDir = 1
  ;(columns || []).forEach((c) => { const th = el('th', c.num ? 'aa-num' : null, c.label); th.addEventListener('click', () => { sortDir = (sortKey === c.key) ? -sortDir : 1; sortKey = c.key; draw() }); htr.appendChild(th) })
  thead.appendChild(htr); t.appendChild(thead)
  const tbody = el('tbody'); t.appendChild(tbody)
  const draw = () => {
    clear(tbody)
    const data = (rows || []).slice()
    if (sortKey) data.sort((a, b) => { const x = a[sortKey]; const y = b[sortKey]; return (x < y ? -1 : x > y ? 1 : 0) * sortDir })
    for (const r of data) { const tr = el('tr'); (columns || []).forEach((c) => { const v = c.format ? c.format(r[c.key], r) : r[c.key]; tr.appendChild(el('td', c.num ? 'aa-num' : null, v == null ? '' : String(v))) }); tbody.appendChild(tr) }
  }
  draw(); parent.appendChild(t); return t
}

// Horizontal bar chart (divs, no external libs). items: [{ label, value }]; valueFormat optional.
export const barChart = (parent, items, valueFormat) => {
  const list = items || []
  const max = Math.max(1, ...list.map((i) => Number(i.value) || 0))
  const wrap = el('div', 'aa-bars')
  for (const it of list) {
    const row = el('div', 'aa-bar-row')
    row.appendChild(el('div', null, it.label))
    const track = el('div', 'aa-bar-track'); const fill = el('div', 'aa-bar-fill'); fill.style.width = ((Number(it.value) || 0) / max * 100) + '%'; track.appendChild(fill)
    row.appendChild(track)
    row.appendChild(el('div', 'aa-num', valueFormat ? valueFormat(it.value) : fmtNum(it.value)))
    wrap.appendChild(row)
  }
  parent.appendChild(wrap); return wrap
}

export const empty = (parent, msg) => { parent.appendChild(el('div', 'aa-empty', msg || 'No data to show.')) }
export const loading = (parent, msg) => { const l = el('div', 'aa-loading', msg || 'Loading…'); parent.appendChild(l); return l }
`

// index.js stub — replaced by the model's first build. Kept runnable so a freshly-created (unbuilt) app
// doesn't error.
export const INDEX_JS_STUB = `/* global freezr */
import { heading, loading } from './askapp-base.js'
const root = document.getElementById('ask-app')
heading(root, 'Getting ready…')
loading(root, 'Your page is being built.')
`

// ---- Boot dispatcher (the ONLY registered module) ----
// The index page always exists, so we run everything through it. On ?action=probe it hands off to the
// data-probe runner; otherwise it loads the real app entry (index.js). PROTECTED — never model-written.
export const BOOT_JS = `// freezr ask-app boot — do NOT edit. Routes the index page to the app or the data-probe runner.
const action = new URLSearchParams(location.search).get('action')

// Runtime error capture (freezr_creator_selfcheck_plan_v1.md B3). Without this, a throw or a
// syntax error in index.js just leaves a blank page: the dynamic import rejects, nothing is
// recorded, and the user has to describe the breakage in prose. We stash the messages in
// localStorage — the same handoff the data probe already uses — and the ask builder reads them
// on its next load so the model is TOLD what broke. Report-only: it changes no app behaviour.
const FZ_ERR_KEY = 'freezr_ask_runtime_errors'
const fzRecordError = (kind, message, extra) => {
  try {
    const app = (window.freezrMeta && window.freezrMeta.appName) || (location.pathname.split('/')[2] || '')
    const prev = JSON.parse(localStorage.getItem(FZ_ERR_KEY) || '[]')
    prev.push(Object.assign({
      app: app,
      kind: kind,
      message: String(message == null ? '' : message).slice(0, 500),
      at: new Date().toISOString()
    }, extra || {}))
    localStorage.setItem(FZ_ERR_KEY, JSON.stringify(prev.slice(-10)))
  } catch (e) { /* storage unavailable — nothing to do */ }
}
window.addEventListener('error', (ev) => {
  if (ev && ev.target && ev.target !== window && ev.target.tagName) {
    fzRecordError('resource', 'Failed to load ' + (ev.target.src || ev.target.href || ev.target.tagName))
    return
  }
  fzRecordError('error', ev && ev.message, {
    source: ev && ev.filename ? String(ev.filename).split('/').pop() : undefined,
    line: ev && ev.lineno ? ev.lineno : undefined,
    column: ev && ev.colno ? ev.colno : undefined,
    stackHead: ev && ev.error && ev.error.stack ? String(ev.error.stack).split('\\n').slice(0, 3).join(' | ').slice(0, 400) : undefined
  })
}, true)
window.addEventListener('unhandledrejection', (ev) => {
  const r = ev && ev.reason
  fzRecordError('unhandledrejection', (r && r.message) || r, {
    stackHead: r && r.stack ? String(r.stack).split('\\n').slice(0, 3).join(' | ').slice(0, 400) : undefined
  })
})

if (action === 'probe') {
  import('./askapp-probe.js')
} else {
  // A small "ask" button (top-left, mirroring the /creator/ask page) to jump back to editing this app.
  try {
    const appName = (window.freezrMeta && window.freezrMeta.appName) || (location.pathname.split('/')[2] || '')
    if (appName) {
      const a = document.createElement('a')
      a.className = 'aa-ask-btn'; a.textContent = 'ask'; a.title = 'Edit this ask-app'
      a.href = '/creator/ask?app=' + encodeURIComponent(appName)
      document.body.appendChild(a)
    }
  } catch (e) { /* non-fatal */ }
  // .catch is the important half: a syntax error or a failed import inside index.js rejects HERE,
  // and without this handler the rejection is swallowed and the page is silently blank.
  import('./index.js').catch((e) => {
    fzRecordError('import_failed', (e && e.message) || e, {
      stackHead: e && e.stack ? String(e.stack).split('\\n').slice(0, 3).join(' | ').slice(0, 400) : undefined
    })
    try {
      const root = document.getElementById('ask-app')
      if (root && !root.textContent.trim()) {
        root.innerHTML = '<p class="aa-muted">This page could not start. Open it from the ask builder and the assistant will be shown the error.</p>'
      }
    } catch (e2) { /* non-fatal */ }
  })
}
`

// ---- Data-probe runner (loaded by boot on /apps/<app>/index?action=probe) ----
// Runs a structured query AS THIS APP (its own token + granted, read-only permissions — no new
// privileged path), caps to 5 records, applies the app's own decrypt/shape hook if present, and asks the
// user to approve sharing the result before it goes anywhere. PROTECTED — the model never writes this.
export const PROBE_JS = `/* global freezr */
// Protected ask-app probe runner. Runs a structured query with this app's own permissions, caps at 5,
// applies the app's shape hook, and requires the user to approve the result before it is shared back.
const root = document.getElementById('ask-app')
const params = new URLSearchParams(location.search)
const RESULT_KEY = 'freezr_ask_probe_result'
let req = {}
try { req = JSON.parse(decodeURIComponent(escape(atob(params.get('req') || '')))) } catch (e) { req = {} }
const finish = (payload) => { try { localStorage.setItem(RESULT_KEY, JSON.stringify(payload)) } catch (e) {} location.href = '/creator/ask?app=' + encodeURIComponent(req.app_name || '') + '&resume_probe=1' }

const run = async () => {
  root.innerHTML = '<p class="aa-muted">Looking up your data…</p>'
  const cap = Math.min(Math.max(1, Number(req.count) || 5), 5) // hard cap 5, enforced here (not trusting the request)
  let rows = []
  try { rows = await freezr.query(req.app_table, req.filter || {}, { count: cap }) } catch (e) { finish({ ok: false, error: 'Query failed: ' + (e && e.message ? e.message : e) }); return }
  rows = (rows || []).slice(0, cap)
  try { const m = await import('./askapp-probe-hook.js'); if (m && typeof m.shapeProbeRows === 'function') rows = m.shapeProbeRows(rows) } catch (e) { /* no hook: raw rows (may be encrypted) */ }
  renderGate(rows, cap)
}
const renderGate = (rows, cap) => {
  root.innerHTML = ''
  const h = document.createElement('h1'); h.textContent = 'Share this data with your LLM?'; root.appendChild(h)
  const d = document.createElement('p'); d.className = 'aa-muted'
  d.textContent = (req.description || 'Your LLM asked to look at some of your data.') + ' — showing ' + rows.length + ' record' + (rows.length === 1 ? '' : 's') + ' from ' + (req.app_table || '')
  root.appendChild(d)
  const pre = document.createElement('pre')
  pre.textContent = JSON.stringify(rows, null, 2)
  pre.setAttribute('style', 'background:#0f1728;color:#cdd6e6;padding:12px;border-radius:8px;max-height:52vh;overflow:auto;font-size:12px;white-space:pre-wrap;word-break:break-word')
  root.appendChild(pre)
  const bar = document.createElement('div'); bar.setAttribute('style', 'display:flex;gap:8px;margin-top:14px')
  const share = document.createElement('button'); share.textContent = 'Share with LLM'
  share.setAttribute('style', 'background:#2f6fed;color:#fff;border:none;border-radius:8px;padding:8px 16px;font-size:14px;cursor:pointer')
  share.onclick = () => finish({ ok: true, rows, query: { app_table: req.app_table, filter: req.filter || {}, count: cap } })
  const cancel = document.createElement('button'); cancel.textContent = 'Cancel'
  cancel.setAttribute('style', 'background:#eef2f8;color:#2f4066;border:none;border-radius:8px;padding:8px 16px;font-size:14px;cursor:pointer')
  cancel.onclick = () => finish({ ok: false, declined: true })
  bar.appendChild(share); bar.appendChild(cancel); root.appendChild(bar)
}
run()
`

// The app-specific probe transform. Written by the model at build time ONLY if the app's data needs
// decrypting/reshaping (e.g. rows.map(r => vcEncryptor.decryptFor(r))). Default: return rows unchanged.
export const PROBE_HOOK_STUB = `// App-specific probe transform. Signature: (rows) => rows.
// The model overwrites this at build time if the app's data must be decrypted/reshaped to be readable.
export const shapeProbeRows = (rows) => rows
`

// The fixed pages skeleton + the initial files[] (path + description) the client maintains thereafter.
export const askAppManifestSkeleton = (displayName) => ({
  // The only registered module is the boot dispatcher; it loads index.js (the app) or the probe runner.
  pages: {
    index: { page_title: displayName, html_file: 'index.html', css_files: ['askapp-base.css', 'app.css'], modules: ['askapp-boot.js'] }
  },
  files: [
    { path: 'index.html', description: 'Standard ask-app shell — a single #ask-app container (managed by freezr).' },
    { path: 'askapp-base.css', description: 'Shared base styles (do not edit).' },
    { path: 'askapp-base.js', description: 'Shared UI helpers: table, barChart, statRow, formatters (do not edit).' },
    { path: 'app.css', description: 'App-specific styles.' },
    { path: 'index.js', description: 'App entry point.' },
    { path: 'askapp-boot.js', description: 'Boot dispatcher (managed by freezr; do not edit).' },
    { path: 'askapp-probe.js', description: 'Data-check runner (managed by freezr; do not edit).' },
    { path: 'askapp-probe-hook.js', description: 'App-specific transform applied to probed rows (e.g. decryption).' }
  ]
})

// The files written to disk when an ask-app is created.
export const askAppScaffoldFiles = () => [
  { path: 'index.html', content: SHELL_HTML },
  { path: 'askapp-base.css', content: BASE_CSS },
  { path: 'askapp-base.js', content: BASE_JS },
  { path: 'app.css', content: '/* app-specific styles — reuse askapp-base.css classes first; only add what it lacks */\n' },
  { path: 'index.js', content: INDEX_JS_STUB },
  { path: 'askapp-boot.js', content: BOOT_JS },
  { path: 'askapp-probe.js', content: PROBE_JS },
  { path: 'askapp-probe-hook.js', content: PROBE_HOOK_STUB }
]

// Base files the LLM must never overwrite (shell logic + boot + probe runner). The probe HOOK is model-writable.
export const PROTECTED_ASKAPP_FILES = ['askapp-base.css', 'askapp-base.js', 'askapp-boot.js', 'askapp-probe.js']

// The protected scaffold files that get REWRITTEN on refresh (to propagate fixes + migrate old apps).
// Excludes index.html (the model may customise the shell), app.css / index.js (model-owned) and the
// probe hook (model-owned). Used by refreshAskAppScaffold.
export const askAppProtectedScaffoldFiles = () => [
  { path: 'askapp-base.css', content: BASE_CSS },
  { path: 'askapp-base.js', content: BASE_JS },
  { path: 'askapp-boot.js', content: BOOT_JS },
  { path: 'askapp-probe.js', content: PROBE_JS }
]
export const ASKAPP_INDEX_MODULES = ['askapp-boot.js']
