// freezr.info - mongo_utils.mjs
// Utility functions for MongoDB operations

import config from '../../../common/helpers/config.mjs'
import { ObjectId } from 'mongodb'

const fullOACName = function (ownerAppTable, addOwnerAtStart) { // addOwnerAtStart used for unified db
  // onsole.log('mongo - fullOACName ownerAppTable ', ownerAppTable)

  if (!ownerAppTable) console.warn('fullOACName', 'Mongp collection failure - need ownerAppTable')
  if (!ownerAppTable) throw new Error('Mongo collection failure - need ownerAppTable')
  const appTable = ownerAppTable.app_table || (ownerAppTable.app_name + (ownerAppTable.collection_name ? ('_' + ownerAppTable.collection_name) : ''))
  if (!appTable || !ownerAppTable.owner) throw new Error('Mongo collection failure - need app name and an owner for ' + ownerAppTable.owner + '__' + ownerAppTable.app_name + '_' + ownerAppTable.collection_name)
  return ((addOwnerAtStart ? (ownerAppTable.owner + '__') : '') + appTable).replace(/\./g, '_')
}

const hasUnifiedStrategy = function (dbParams, owner) {
  if (!dbParams.dbUnificationStrategy || dbParams.dbUnificationStrategy === 'db') return false
  if (dbParams.dbUnificationStrategy === 'all') return true
  const notReservedid = config.RESERVED_IDS.indexOf(owner) < 0
  // onsole.log('hasUnifiedStrategy is system app ' + owner, { owner, notReservedid })
  if (dbParams.dbUnificationStrategy === 'allButAdmin') return (notReservedid)
  throw new Error('Unknown dbUnificationStrategy: ' + dbParams.dbUnificationStrategy)
  // return (Boolean(dbParams.dbUnificationStrategy) && dbParams.dbUnificationStrategy !== 'db') ||
  //    (dbParams.useUnifiedCollection && helpers.RESERVED_IDS.indexOf(owner) < 0) // ie unified collecions only valid for non-system users
}

/**
 * Checks if an ID is autogenerated by MongoDB (ObjectId)
 * @param {string|ObjectId} id - The ID to check
 * @returns {boolean} - True if the ID is autogenerated, false otherwise
 */
const isAutogenerated = function (id) {
  if (!id) return false
  
  // If it's already an ObjectId, it's autogenerated
  if (id instanceof ObjectId) return true
  
  // If it's a string, check if it's a valid ObjectId
  if (typeof id === 'string') {
    // Check if it's a valid ObjectId format (24 hex characters)
    if (!ObjectId.isValid(id)) return false
    
    // Check if the string representation of a new ObjectId matches the original string
    // This helps distinguish between autogenerated ObjectIds and strings that just happen to have the correct format
    try {
      return new ObjectId(id).toString() === id;
    } catch (e) {
      return false;
    }
  }
  
  return false
}

/**
 * Returns a revised ID with the prefix if needed
 * @param {string|ObjectId} id - The original ID
 * @param {Object} oat - The ownerAppTable object
 * @returns {string|ObjectId} - The revised ID
 */
const getRevisedIdWithOatAdded = function (id, oat) {
  if (!id) return id
  
  // If it's autogenerated, return as is
  if (isAutogenerated(id)) return id
  
  // If it's a string and doesn't start with the prefix, add the prefix
  if (typeof id === 'string') {
    const prefix = oat.owner + '__' + fullOACName(oat, false) + '__'
    if (!id.startsWith(prefix)) {
      return prefix + id
    }
  }
  
  return id
}

/**
 * Strip the unified-DB prefix (owner__appTable__) from an ID, if present.
 * Inverse of getRevisedIdWithOatAdded — use when a record's `_id` from a
 * unified Mongo collection needs to be treated as the original
 * application-level id (e.g. a file path).
 * Safe to call on already-clean ids and on autogenerated ObjectIds.
 * @param {string|ObjectId} id - The (possibly prefixed) ID
 * @param {Object} oat - The ownerAppTable object
 * @returns {string|ObjectId} - The original ID without the prefix
 */
const getOrigIdWithOatRemoved = function (id, oat) {
  if (!id) return id
  if (isAutogenerated(id)) return id
  if (typeof id !== 'string' || !oat || !oat.owner) return id
  const prefix = oat.owner + '__' + fullOACName(oat, false) + '__'
  if (id.startsWith(prefix)) {
    return id.substring(prefix.length)
  }
  return id
}

/**
 * Strip the unified-DB prefix from a freezr publicid of the form
 * `@<owner>/<appTable>/<rest>`. Returns `@<owner>/<appTable>/<rest-without-prefix>`
 * when `<rest>` begins with `<owner>__<appTable-with-dots-as-underscores>__`.
 *
 * Defensive helper for serving public records that were written before
 * the prefix-stripping fix in shareRecords (their `_id` and any embedded
 * publicid in `fileStructure.css/js[]` carry the prefix). Idempotent and
 * safe on clean publicids.
 *
 * @param {string} publicid - Public record id / URL slug
 * @returns {string} Cleaned publicid
 */
const stripUnifiedPrefixFromPublicid = function (publicid) {
  if (!publicid || typeof publicid !== 'string') return publicid
  if (!publicid.startsWith('@')) return publicid
  const firstSlash = publicid.indexOf('/')
  if (firstSlash < 1) return publicid
  const owner = publicid.substring(1, firstSlash)
  const secondSlash = publicid.indexOf('/', firstSlash + 1)
  if (secondSlash < 0) return publicid
  const appTable = publicid.substring(firstSlash + 1, secondSlash)
  const rest = publicid.substring(secondSlash + 1)
  const prefix = owner + '__' + appTable.replace(/\./g, '_') + '__'
  if (rest.startsWith(prefix)) {
    return '@' + owner + '/' + appTable + '/' + rest.substring(prefix.length)
  }
  return publicid
}

export { fullOACName, hasUnifiedStrategy, isAutogenerated, getRevisedIdWithOatAdded, getOrigIdWithOatRemoved, stripUnifiedPrefixFromPublicid }
