// Generates freezr-context.md — a single bundle of the creator's LLM context
// (rules + API reference + permissions) for use as CLAUDE.md context when
// developing a freezr app in a standalone repo (e.g. with Claude Code).
//
// Source of truth = the longText exports in this folder. Re-run after editing
// any of them. Output is written next to freezrApiV2.js so it is also served
// publicly (e.g. https://<server>/app_files/info.freezr.public/freezr-context.md).
//
// Run from anywhere:
//   node "freezrsystmapps/info.freezr.creator/modules/longTexts/genContext.js"

import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

import { CHAT_PROMPT } from './chatPrompt.js'
import { API_REFERENCE } from './apiReference.js'
import { PERMISSION_PROMPT } from './permissionPrompt.js'

const here = dirname(fileURLToPath(import.meta.url))
const outPath = resolve(here, '../../../info.freezr.public/public/freezr-context.md')

const bundle = [
  '# freezr App Development Context',
  '',
  '_Generated by `info.freezr.creator/modules/longTexts/genContext.js` from the freezr',
  'creator\'s own LLM context. Do NOT edit by hand — edit the longText source files and',
  're-run the generator. This is the same guidance the in-browser creator gives its model._',
  '',
  '## How to use this file with an AI coding assistant',
  '',
  'Drop a copy of `freezr-context.md` into the root of your app repo, then:',
  '',
  '- **Claude Code:** create a `CLAUDE.md` at the repo root containing one line — `@freezr-context.md`. It is auto-loaded every session.',
  '- **Cursor:** save this as `.cursor/rules/freezr.mdc` (or add a rule pointing to `freezr-context.md`) so it is attached to the project context.',
  '- **GitHub Copilot / Codex / other agents:** rename or symlink this file to `AGENTS.md` at the repo root — the common cross-tool convention most agents auto-read.',
  '- **ChatGPT (web):** upload `freezr-context.md` to your conversation or add it to a Project\'s files, and tell the model to follow it when writing freezr app code.',
  '',
  '---',
  '',
  '## Rules & Conventions',
  '',
  CHAT_PROMPT.trim(),
  '',
  '---',
  '',
  '## API Reference',
  '',
  API_REFERENCE.trim(),
  '',
  '---',
  '',
  '## Permissions',
  '',
  PERMISSION_PROMPT.trim(),
  ''
].join('\n')

writeFileSync(outPath, bundle)
console.log(`Wrote ${bundle.length} bytes to ${outPath}`)
